kind: Secret
apiVersion: v1
metadata:
  name: sample-secret
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    avp.kubernetes.io/path: prod/secret
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  sample-secret: <foo>
